/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.util.Date;



/**
 *
 * @author Titis Sukmono
 */
public class Menu extends javax.swing.JFrame {
    // waktu sekarang 
     private void setJam(){
        ActionListener listener = new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent evt) {
                jam.setText(new WaktuSekarang().getWkt());
            }
        };
        new Timer(1000, listener).start();
    }
     
     public class WaktuSekarang {
    private Date wkt;
    private String $jam = "", $menit = "", $detik = "";
    public String getWkt(){
        wkt = new Date();
        int jam = wkt.getHours();
        int menit = wkt.getMinutes();
        int detik = wkt.getSeconds();
        if(jam <= 9)$jam = "0";
        if(menit <= 9)$menit = "0";
        if(detik <= 9)$detik = "0";
        return $jam + Integer.toString(jam)+":"+$menit + Integer.toString(menit)+":"+$detik + Integer.toString(detik);
    }
    public String getTgl(){
        wkt = new Date();
        java.text.SimpleDateFormat tgl = new java.text.SimpleDateFormat("dd/MM/yyyy");
        return tgl.format(wkt);
    }
}
    //

   static boolean maximixed = true;
    int xMouse;
    int yMouse;
       

 
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(this);
         setJam();
       
        
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dekstoppane = new javax.swing.JDesktopPane();
        panelUtama = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jam = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        btnMasterBuku = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        panelBuku = new javax.swing.JPanel();
        btnjnisbuku = new javax.swing.JButton();
        btnDatabuku = new javax.swing.JButton();
        panelTransaksi = new javax.swing.JPanel();
        btnmenuTransaksi = new javax.swing.JButton();
        btnmenudetailTransaksi = new javax.swing.JButton();
        panelLaporan = new javax.swing.JPanel();
        btnLapJnsBuku = new javax.swing.JButton();
        btnLapDatabuku = new javax.swing.JButton();
        btnLapTransaksi = new javax.swing.JButton();
        icon = new javax.swing.JLabel();
        menubar = new javax.swing.JMenuBar();
        jadminsrator = new javax.swing.JMenu();
        mnutambahadmin = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        dekstoppane.setMaximumSize(new java.awt.Dimension(1600, 1600));
        dekstoppane.setMinimumSize(new java.awt.Dimension(1600, 1600));

        panelUtama.setBackground(new java.awt.Color(255, 255, 255));
        panelUtama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelUtamaMouseClicked(evt);
            }
        });

        panelHeader.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Open_Book_50px.png"))); // NOI18N
        jLabel1.setText("APLIKASI PENJUALAN BUKU");

        jam.setBackground(new java.awt.Color(0, 204, 204));
        jam.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jam.setForeground(new java.awt.Color(255, 255, 255));
        jam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_clock_50px_1.png"))); // NOI18N
        jam.setOpaque(true);

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addGap(506, 506, 506)
                .addComponent(jLabel1)
                .addGap(275, 275, 275)
                .addComponent(jam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(889, 889, 889))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jam, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jam.setText(new WaktuSekarang().getWkt());
        jam.setPreferredSize(new java.awt.Dimension(100,22));

        panelMenu.setBackground(new java.awt.Color(0, 204, 204));

        btnMasterBuku.setBackground(new java.awt.Color(0, 153, 153));
        btnMasterBuku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMasterBuku.setForeground(new java.awt.Color(255, 255, 255));
        btnMasterBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_book_50px.png"))); // NOI18N
        btnMasterBuku.setText("  Buku");
        btnMasterBuku.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnMasterBuku.setContentAreaFilled(false);
        btnMasterBuku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMasterBuku.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMasterBuku.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMasterBuku.setOpaque(true);
        btnMasterBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMasterBukuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMasterBukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMasterBukuMouseExited(evt);
            }
        });
        btnMasterBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasterBukuActionPerformed(evt);
            }
        });

        btnTransaksi.setBackground(new java.awt.Color(0, 153, 153));
        btnTransaksi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_transfer_between_users_50px.png"))); // NOI18N
        btnTransaksi.setText("  Transaksi");
        btnTransaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnTransaksi.setContentAreaFilled(false);
        btnTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTransaksi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnTransaksi.setOpaque(true);
        btnTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseExited(evt);
            }
        });
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });

        btnLaporan.setBackground(new java.awt.Color(0, 153, 153));
        btnLaporan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLaporan.setForeground(new java.awt.Color(255, 255, 255));
        btnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_report_card_50px.png"))); // NOI18N
        btnLaporan.setText("  Laporan");
        btnLaporan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLaporan.setContentAreaFilled(false);
        btnLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLaporan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLaporan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLaporan.setOpaque(true);
        btnLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLaporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLaporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLaporanMouseExited(evt);
            }
        });
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnMasterBuku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTransaksi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(btnLaporan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnMasterBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBuku.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnjnisbuku.setBackground(new java.awt.Color(0, 153, 153));
        btnjnisbuku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnjnisbuku.setForeground(new java.awt.Color(255, 255, 255));
        btnjnisbuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_book_shelf_50px_2.png"))); // NOI18N
        btnjnisbuku.setText("Jenis Buku");
        btnjnisbuku.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnjnisbuku.setContentAreaFilled(false);
        btnjnisbuku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnjnisbuku.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnjnisbuku.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnjnisbuku.setOpaque(true);
        btnjnisbuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnjnisbukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnjnisbukuMouseExited(evt);
            }
        });
        btnjnisbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjnisbukuActionPerformed(evt);
            }
        });

        btnDatabuku.setBackground(new java.awt.Color(0, 153, 153));
        btnDatabuku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDatabuku.setForeground(new java.awt.Color(255, 255, 255));
        btnDatabuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_books_50px.png"))); // NOI18N
        btnDatabuku.setText("  Data Buku");
        btnDatabuku.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnDatabuku.setContentAreaFilled(false);
        btnDatabuku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDatabuku.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDatabuku.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDatabuku.setOpaque(true);
        btnDatabuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDatabukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDatabukuMouseExited(evt);
            }
        });
        btnDatabuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatabukuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBukuLayout = new javax.swing.GroupLayout(panelBuku);
        panelBuku.setLayout(panelBukuLayout);
        panelBukuLayout.setHorizontalGroup(
            panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnjnisbuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBukuLayout.createSequentialGroup()
                .addComponent(btnDatabuku, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelBukuLayout.setVerticalGroup(
            panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBukuLayout.createSequentialGroup()
                .addComponent(btnjnisbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDatabuku, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelTransaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnmenuTransaksi.setBackground(new java.awt.Color(0, 153, 153));
        btnmenuTransaksi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnmenuTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        btnmenuTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_data_in_both_directions_50px_3.png"))); // NOI18N
        btnmenuTransaksi.setText("   Transaksi");
        btnmenuTransaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnmenuTransaksi.setContentAreaFilled(false);
        btnmenuTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmenuTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnmenuTransaksi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnmenuTransaksi.setOpaque(true);
        btnmenuTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnmenuTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnmenuTransaksiMouseExited(evt);
            }
        });
        btnmenuTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuTransaksiActionPerformed(evt);
            }
        });

        btnmenudetailTransaksi.setBackground(new java.awt.Color(0, 153, 153));
        btnmenudetailTransaksi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnmenudetailTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        btnmenudetailTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_purchase_order_50px_1.png"))); // NOI18N
        btnmenudetailTransaksi.setText(" Detail Transaksi");
        btnmenudetailTransaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnmenudetailTransaksi.setContentAreaFilled(false);
        btnmenudetailTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmenudetailTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnmenudetailTransaksi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnmenudetailTransaksi.setOpaque(true);
        btnmenudetailTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnmenudetailTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnmenudetailTransaksiMouseExited(evt);
            }
        });
        btnmenudetailTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenudetailTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTransaksiLayout = new javax.swing.GroupLayout(panelTransaksi);
        panelTransaksi.setLayout(panelTransaksiLayout);
        panelTransaksiLayout.setHorizontalGroup(
            panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnmenudetailTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(btnmenuTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTransaksiLayout.setVerticalGroup(
            panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransaksiLayout.createSequentialGroup()
                .addComponent(btnmenuTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnmenudetailTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelLaporan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnLapJnsBuku.setBackground(new java.awt.Color(0, 153, 153));
        btnLapJnsBuku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLapJnsBuku.setForeground(new java.awt.Color(255, 255, 255));
        btnLapJnsBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_chrome_reader_mode_50px.png"))); // NOI18N
        btnLapJnsBuku.setText(" Laporan Jenis Buku");
        btnLapJnsBuku.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLapJnsBuku.setContentAreaFilled(false);
        btnLapJnsBuku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLapJnsBuku.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLapJnsBuku.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLapJnsBuku.setOpaque(true);
        btnLapJnsBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLapJnsBukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLapJnsBukuMouseExited(evt);
            }
        });
        btnLapJnsBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapJnsBukuActionPerformed(evt);
            }
        });

        btnLapDatabuku.setBackground(new java.awt.Color(0, 153, 153));
        btnLapDatabuku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLapDatabuku.setForeground(new java.awt.Color(255, 255, 255));
        btnLapDatabuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_book_stack_50px.png"))); // NOI18N
        btnLapDatabuku.setText("  Laporan Data Buku");
        btnLapDatabuku.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLapDatabuku.setContentAreaFilled(false);
        btnLapDatabuku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLapDatabuku.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLapDatabuku.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLapDatabuku.setOpaque(true);
        btnLapDatabuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLapDatabukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLapDatabukuMouseExited(evt);
            }
        });
        btnLapDatabuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapDatabukuActionPerformed(evt);
            }
        });

        btnLapTransaksi.setBackground(new java.awt.Color(0, 153, 153));
        btnLapTransaksi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLapTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        btnLapTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_bill_50px.png"))); // NOI18N
        btnLapTransaksi.setText("   Laporan Transaksi");
        btnLapTransaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLapTransaksi.setContentAreaFilled(false);
        btnLapTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLapTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLapTransaksi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLapTransaksi.setOpaque(true);
        btnLapTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLapTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLapTransaksiMouseExited(evt);
            }
        });
        btnLapTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLaporanLayout = new javax.swing.GroupLayout(panelLaporan);
        panelLaporan.setLayout(panelLaporanLayout);
        panelLaporanLayout.setHorizontalGroup(
            panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLapDatabuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLapJnsBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(btnLapTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLaporanLayout.setVerticalGroup(
            panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLaporanLayout.createSequentialGroup()
                .addComponent(btnLapJnsBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnLapDatabuku, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnLapTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Book_Shelf_500px.png"))); // NOI18N
        icon.setToolTipText("");

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1020, 1020, 1020))
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUtamaLayout.createSequentialGroup()
                        .addComponent(panelBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(panelTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(45, 45, 45)
                        .addComponent(panelLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(713, 713, 713))))
        );

        dekstoppane.setLayer(panelUtama, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dekstoppaneLayout = new javax.swing.GroupLayout(dekstoppane);
        dekstoppane.setLayout(dekstoppaneLayout);
        dekstoppaneLayout.setHorizontalGroup(
            dekstoppaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dekstoppaneLayout.createSequentialGroup()
                .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3191, 3191, 3191))
        );
        dekstoppaneLayout.setVerticalGroup(
            dekstoppaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dekstoppaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );

        menubar.setBackground(new java.awt.Color(0, 255, 0));
        menubar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 51)));

        jadminsrator.setText("Adminstrator");

        mnutambahadmin.setText("Tambah Admin");
        mnutambahadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnutambahadminActionPerformed(evt);
            }
        });
        jadminsrator.add(mnutambahadmin);
        jadminsrator.add(jSeparator2);

        mnuLogout.setText("Logout");
        mnuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogoutActionPerformed(evt);
            }
        });
        jadminsrator.add(mnuLogout);

        menubar.add(jadminsrator);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dekstoppane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dekstoppane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1557, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogoutActionPerformed
   int confirm=  JOptionPane.showConfirmDialog(this, "apakah yakin keluar","konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (confirm== JOptionPane.YES_OPTION) {
            System.exit(0);
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_mnuLogoutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       panelTransaksi.setVisible(false);
        panelLaporan.setVisible(false);
        panelBuku.setVisible(false);

         btnDatabuku.setVisible(false);
         btnjnisbuku.setVisible(false);
         
         
         btnLapDatabuku.setVisible(false);
         btnLapJnsBuku.setVisible(false);
         btnLapTransaksi.setVisible(false);
         
        btnmenudetailTransaksi.setVisible(false);
        btnmenuTransaksi.setVisible(false);
         setExtendedState(Menu.MAXIMIZED_BOTH);

        
    }//GEN-LAST:event_formWindowOpened

    private void mnutambahadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnutambahadminActionPerformed
    new admin(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_mnutambahadminActionPerformed

    private void panelUtamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUtamaMouseClicked
        panelBuku.setVisible(false);
        panelTransaksi.setVisible(false);
        panelLaporan.setVisible(false);
    }//GEN-LAST:event_panelUtamaMouseClicked

    private void btnLapTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapTransaksiActionPerformed
        panelLaporan.setVisible(false);
             new LaporanTransaksi(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnLapTransaksiActionPerformed

    private void btnLapTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapTransaksiMouseExited
        btnLapTransaksi.setForeground(Color.white);
        btnLapTransaksi.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnLapTransaksiMouseExited

    private void btnLapTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapTransaksiMouseEntered
        btnLapTransaksi.setForeground(Color.red);
        btnLapTransaksi.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnLapTransaksiMouseEntered

    private void btnLapDatabukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapDatabukuActionPerformed
        panelLaporan.setVisible(false);
        new LaporanDataBuku(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnLapDatabukuActionPerformed

    private void btnLapDatabukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapDatabukuMouseExited
        btnLapDatabuku.setForeground(Color.white);
        btnLapDatabuku.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnLapDatabukuMouseExited

    private void btnLapDatabukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapDatabukuMouseEntered
        btnLapDatabuku.setForeground(Color.red);
        btnLapDatabuku.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnLapDatabukuMouseEntered

    private void btnLapJnsBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapJnsBukuActionPerformed
        panelLaporan.setVisible(false);
       
        new LaporanJenisBuku(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnLapJnsBukuActionPerformed

    private void btnLapJnsBukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapJnsBukuMouseExited
        btnLapJnsBuku.setForeground(Color.white);
        btnLapJnsBuku.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnLapJnsBukuMouseExited

    private void btnLapJnsBukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapJnsBukuMouseEntered
        btnLapJnsBuku.setForeground(Color.red);
        btnLapJnsBuku.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnLapJnsBukuMouseEntered

    private void btnmenudetailTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenudetailTransaksiActionPerformed
        panelTransaksi.setVisible(false);
        new Detail_Transaksi(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnmenudetailTransaksiActionPerformed

    private void btnmenudetailTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenudetailTransaksiMouseExited
        btnmenudetailTransaksi.setForeground(Color.white);
        btnmenudetailTransaksi.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnmenudetailTransaksiMouseExited

    private void btnmenudetailTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenudetailTransaksiMouseEntered
        btnmenudetailTransaksi.setForeground(Color.red);
        btnmenudetailTransaksi.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnmenudetailTransaksiMouseEntered

    private void btnmenuTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuTransaksiActionPerformed
        panelTransaksi.setVisible(false);
        new Transaksi(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnmenuTransaksiActionPerformed

    private void btnmenuTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenuTransaksiMouseExited
        btnmenuTransaksi.setForeground(Color.white);
        btnmenuTransaksi.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnmenuTransaksiMouseExited

    private void btnmenuTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenuTransaksiMouseEntered
        btnmenuTransaksi.setForeground(Color.red);
        btnmenuTransaksi.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnmenuTransaksiMouseEntered

    private void btnDatabukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatabukuActionPerformed
        panelBuku.setVisible(false);
        new dataBuku(this, rootPaneCheckingEnabled).show();

    }//GEN-LAST:event_btnDatabukuActionPerformed

    private void btnDatabukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDatabukuMouseExited
        btnDatabuku.setForeground(Color.white);
        btnDatabuku.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnDatabukuMouseExited

    private void btnDatabukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDatabukuMouseEntered
        btnDatabuku.setForeground(Color.red);
        btnDatabuku.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnDatabukuMouseEntered

    private void btnjnisbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjnisbukuActionPerformed
        panelBuku.setVisible(false);
        new jenisbuku(this, rootPaneCheckingEnabled).show();
        //        new dataSupplier(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnjnisbukuActionPerformed

    private void btnjnisbukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjnisbukuMouseExited
        btnjnisbuku.setForeground(Color.white);
        btnjnisbuku.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnjnisbukuMouseExited

    private void btnjnisbukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnjnisbukuMouseEntered
        btnjnisbuku.setForeground(Color.red);
        btnjnisbuku.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnjnisbukuMouseEntered

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLaporanActionPerformed

    private void btnLaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseExited

        btnLaporan.setForeground(Color.white);
        btnLaporan.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnLaporanMouseExited

    private void btnLaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseEntered
        panelLaporan.setVisible(true);
        panelTransaksi.setVisible(false);
        panelBuku.setVisible(false);
        btnLapDatabuku.setVisible(true);
        btnLapJnsBuku.setVisible(true);
        btnLapTransaksi.setVisible(true);
        btnLaporan.setForeground(Color.red);
        btnLaporan.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnLaporanMouseEntered

    private void btnLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseClicked
        panelLaporan.setVisible(true);
        panelTransaksi.setVisible(false);
        panelBuku.setVisible(false);
        btnLapDatabuku.setVisible(true);
        btnLapJnsBuku.setVisible(true);
        btnLapTransaksi.setVisible(true);
    }//GEN-LAST:event_btnLaporanMouseClicked

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        btnmenuTransaksi.setVisible(true);
        btnmenudetailTransaksi.setVisible(true);
        panelTransaksi.setVisible(true);
        panelBuku.setVisible(false);
        panelLaporan.setVisible(false);
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseExited
        btnTransaksi.setForeground(Color.white);
        btnTransaksi.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnTransaksiMouseExited

    private void btnTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseEntered
        btnTransaksi.setForeground(Color.red);
        btnTransaksi.setBackground(new Color(0,153,153));
        btnmenuTransaksi.setVisible(true);
        btnmenudetailTransaksi.setVisible(true);
        panelTransaksi.setVisible(true);
        panelBuku.setVisible(false);
        panelLaporan.setVisible(false);
    }//GEN-LAST:event_btnTransaksiMouseEntered

    private void btnTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseClicked
        btnmenuTransaksi.setVisible(true);
        btnmenudetailTransaksi.setVisible(true);
        panelTransaksi.setVisible(true);
        panelBuku.setVisible(false);
        panelLaporan.setVisible(false);
    }//GEN-LAST:event_btnTransaksiMouseClicked

    private void btnMasterBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasterBukuActionPerformed
        btnDatabuku.setVisible(true);
        btnjnisbuku.setVisible(true);
        panelBuku.setVisible(true);
        panelTransaksi.setVisible(false);
        panelLaporan.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnMasterBukuActionPerformed

    private void btnMasterBukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasterBukuMouseExited
        btnMasterBuku.setForeground(Color.white);
        btnMasterBuku.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnMasterBukuMouseExited

    private void btnMasterBukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasterBukuMouseEntered
        btnDatabuku.setVisible(true);
        btnjnisbuku.setVisible(true);
        panelBuku.setVisible(true);
        panelTransaksi.setVisible(false);
        panelLaporan.setVisible(false);
        btnMasterBuku.setForeground(Color.red);
        btnMasterBuku.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnMasterBukuMouseEntered

    private void btnMasterBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasterBukuMouseClicked
        btnDatabuku.setVisible(true);
        btnjnisbuku.setVisible(true);
        panelBuku.setVisible(true);
        panelTransaksi.setVisible(false);
        panelLaporan.setVisible(false);

    }//GEN-LAST:event_btnMasterBukuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDatabuku;
    public javax.swing.JButton btnLapDatabuku;
    public javax.swing.JButton btnLapJnsBuku;
    public javax.swing.JButton btnLapTransaksi;
    public javax.swing.JButton btnLaporan;
    public javax.swing.JButton btnMasterBuku;
    public javax.swing.JButton btnTransaksi;
    public javax.swing.JButton btnjnisbuku;
    public javax.swing.JButton btnmenuTransaksi;
    public javax.swing.JButton btnmenudetailTransaksi;
    public javax.swing.JDesktopPane dekstoppane;
    public javax.swing.JLabel icon;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JPopupMenu.Separator jSeparator2;
    public javax.swing.JMenu jadminsrator;
    public javax.swing.JLabel jam;
    public javax.swing.JMenuBar menubar;
    public javax.swing.JMenuItem mnuLogout;
    public javax.swing.JMenuItem mnutambahadmin;
    public javax.swing.JPanel panelBuku;
    public javax.swing.JPanel panelHeader;
    public javax.swing.JPanel panelLaporan;
    public javax.swing.JPanel panelMenu;
    public javax.swing.JPanel panelTransaksi;
    public javax.swing.JPanel panelUtama;
    // End of variables declaration//GEN-END:variables
}
